# Generated by Django 2.0.1 on 2018-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='fundRequested',
            field=models.BooleanField(default=False),
        ),
    ]
