# Generated by Django 2.0.1 on 2018-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_travel_fundrequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='inBlockchain',
            field=models.BooleanField(default=False),
        ),
    ]
